name: Preprocess Dataset

on:
  push:
    branches: [ "main" ]
    paths:
      - preprocessing/**
      - spam ham emails_raw/**
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Ghifari-Fikri-Yulistia.py
