name: Preprocess Dataset

on:
  push:
    branches: [ "main" ]
    paths:
      - preprocessing/**
      - spam_ham_emails_raw/**
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Ghifari-Fikri-Yulistia.py
          
      - name: List output
        run: ls -R preprocessing/

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: preprocessing/spam_ham_emails_preprocessing/

      - name: Commit and push preprocessing output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add preprocessing/spam_ham_emails_preprocessing/
          git commit -m "Add preprocessing output from workflow"
          git push
